# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bfcb2954751158db64082c16ae46e87917d68da7834309416e25dae619388e4157c507c145ed1b0de03236560f8d46cac60bf50d4c54f9d35060474a1f370613

test:
  secret_key_base: f5c08863d3518500b5ddde45ed028e28805db9eeb0c67c05674eacc23147f7c8f35c7b26dab7cad86fc3b2bf562ebea493691caaab2302ab3b404300f60adaa7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
